# Generated by Django 5.0 on 2024-04-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucao',
            name='dia',
            field=models.DateTimeField(default='2023-12-18 12:00:00'),
        ),
    ]
