# Generated by Django 5.0 on 2024-05-08 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_evolucao_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_social', models.CharField(blank=True, max_length=100)),
                ('nis', models.CharField(max_length=11, unique=True)),
                ('data_nascimento', models.DateField()),
                ('identidade_genero', models.CharField(choices=[('HCIS', 'Homem cisgênero'), ('MCIS', 'Mulher cisgênero'), ('HTRA', 'Homem transgênero'), ('MTRA', 'Mulher transgênero'), ('NBIN', 'Pessoa não-binária'), ('OUTR', 'Outros')], max_length=4)),
                ('cor_raca', models.CharField(choices=[('BRAN', 'Branco'), ('PRET', 'Preto'), ('PARD', 'Pardo'), ('INDI', 'Indígena'), ('AMAR', 'Amarelo'), ('OUTR', 'Outros')], max_length=4)),
                ('estado_civil', models.CharField(choices=[('SOLT', 'Solteiro'), ('CASA', 'Solteiro'), ('DIVO', 'Solteiro'), ('VIUV', 'Solteiro'), ('UNES', 'Solteiro')], max_length=4)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=15)),
                ('naturalidade', models.CharField(max_length=50)),
                ('tempo_residencia_municipio', models.PositiveIntegerField()),
                ('rg', models.CharField(max_length=20)),
                ('certidao_nascimento_casamento', models.CharField(max_length=20)),
                ('titulo_eleitor', models.CharField(blank=True, max_length=12)),
                ('nivel_escolaridade', models.CharField(choices=[('FUNI', 'Ensino Fundamental Incompleto'), ('FUNC', 'Ensino Fundamental Completo'), ('MEDI', 'Ensino Médio Incompleto'), ('MEDC', 'Ensino Médio Completo'), ('SUPI', 'Ensino Superior Incompleto'), ('SUPC', 'Ensino Superior Completo')], max_length=4)),
                ('ocupacao', models.CharField(max_length=50)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extrema_pobreza', models.BooleanField(default=False)),
                ('pessoa_com_deficiencia', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.populacaousuaria')),
            ],
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_imovel', models.CharField(choices=[('PRO', 'Próprio'), ('ALU', 'Alugado'), ('CES', 'Cessão'), ('POS', 'Posse'), ('INV', 'Invasão'), ('OUT', 'Outro')], max_length=4)),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('numero_comodos', models.PositiveIntegerField()),
                ('material_paredes', models.CharField(choices=[('ALV', 'Alvenaria'), ('MAD', 'Madeira'), ('OUT', 'Outros')], max_length=4)),
                ('material_piso', models.CharField(choices=[('ALV', 'Alvenaria'), ('MAD', 'Madeira'), ('OUT', 'Outros')], max_length=4)),
                ('material_telhado', models.CharField(choices=[('ALV', 'Alvenaria'), ('MAD', 'Madeira'), ('OUT', 'Outros')], max_length=4)),
                ('estado_conservacao', models.CharField(choices=[('BOM', 'Bom'), ('REG', 'Regular'), ('RUI', 'Ruim')], max_length=4)),
                ('fornecimento_agua', models.BooleanField(default=True)),
                ('fornecimento_energia', models.BooleanField(default=True)),
                ('coleta_esgoto', models.BooleanField(default=True)),
                ('coleta_lixo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.populacaousuaria')),
            ],
        ),
    ]
