# Generated by Django 5.0 on 2024-05-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_dadospessoais_residencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadospessoais',
            name='tempo_residencia_municipio',
            field=models.CharField(max_length=200),
        ),
    ]
