# Generated by Django 5.0 on 2024-04-04 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriabeneficio',
            name='titulo',
            field=models.CharField(choices=[('BEN1', 'Solicitação de benefício'), ('ATEN', 'Atendimento do CRAS'), ('ATIV', 'Atividades do CRAS')], max_length=4),
        ),
    ]
